=== leticiarivlop/2122_LMSGI_LeticiaRL/ud04/02/02.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:element name="world">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fila" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="continente" type="xs:string"/>
                            <xs:element name="pais" type="xs:string"/>
                            <xs:element name="capital" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== leticiarivlop/2122_LMSGI_LeticiaRL/ud04/02/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE world [
                <!ELEMENT world (fila+)>
                <!ATTLIST world
                          xmlns:xsi CDATA #IMPLIED
                          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
                <!ELEMENT fila (continente,pais,capital)>
                <!ELEMENT continente (#PCDATA)>
                <!ELEMENT pais (#PCDATA)>
                <!ELEMENT capital (#PCDATA)>
]>

<world xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='02.xsd'>
    <fila>
        <continente>
            Europa
        </continente>
        <pais>
            Alemania
        </pais>
        <capital>
            Berlin
        </capital>
    </fila>
    <fila>
        <continente>
            America
        </continente>
        <pais>
            Argentina
        </pais>
        <capital>
            Buenos Aires
        </capital>
    </fila>
    <fila>
        <continente>
           America
        </continente>
        <pais>
            Bahamas
        </pais>
        <capital>
            Nassau
        </capital>
    </fila>
    <fila>
        <continente>
            Asia
        </continente>
        <pais>
            Afganistan
        </pais>
        <capital>
           Kabul
        </capital>
    </fila>
    <fila>
        <continente>
          Asia
        </continente>
        <pais>
           Arabia Saudita
        </pais>
        <capital>
            Riad
        </capital>
    </fila>
</world>
