<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE receta [
                <!ELEMENT receta (nombre,descripcion?,tiempo,ingredientes,instrucciones)>
                <!ATTLIST receta
                          xmlns:xsi CDATA #IMPLIED
                          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
                <!ATTLIST receta
                          plato (primero|segundo|postre) #REQUIRED>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT descripcion (#PCDATA)>
                <!ELEMENT tiempo EMPTY>
                <!ATTLIST tiempo
                            preparacion CDATA #REQUIRED
                            coccion CDATA #IMPLIED>
                <!ELEMENT ingredientes (ingrediente)+>
                <!ELEMENT ingrediente (nombre,cantidad?)>
                <!ELEMENT nombre1 (#PCDATA)>
                <!ELEMENT cantidad (#PCDATA)>
                <!ATTLIST cantidad
                            unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
                <!ELEMENT instrucciones (paso)+>
                <!ELEMENT paso (#PCDATA)>
]>

<receta plato="primero"
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='11.xsd'>
    <nombre>Rissoto milanesa</nombre>
    <tiempo preparacion="20" coccion="20"/>
    <ingredientes>
        <ingrediente>
            <nombre>arroz</nombre>
            <cantidad unidad="gramos">500</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Cebolla mediana </nombre>
            <cantidad>1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>azafran</nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>queso parmesano</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>mantequilla</nombre>
            <cantidad unidad="gramos">100</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Sal </nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>Pimienta</nombre>
            <cantidad unidad="pizca">1</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>caldo</nombre>
            <cantidad unidad="mililitros">1000</cantidad>
        </ingrediente>
        <ingrediente>
            <nombre>vino blanco</nombre>
            <cantidad unidad="chorro">1</cantidad>
        </ingrediente>
    </ingredientes>
    <instrucciones>
        <paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla.</paso>
        <paso>Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca.</paso>
        <paso>A continuación, incorporamos el arroz, lo sofreímos un poco. </paso>
        <paso> Vamos añadiendo el caldo caliente poco a poco mientras removemos.</paso>
        <paso> Salpimentamos.</paso>
        <paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso.</paso>
        <paso> Servimos enseguida.</paso>
    </instrucciones>
</receta>