=== leticiarivlop/2122_LMSGI_LeticiaRL/html/html/ud04/10/10.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:simpleType name="maxmin">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="-100"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="prediccion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="municipio">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="provincia" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dia" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prob_precipitacion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="estado_cielo">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:integer">
                                            <xs:attribute name="descripcion">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:maxLength value="255"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="viento">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="direccion">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Norte"/>
                                                    <xs:enumeration value="Sur"/>
                                                    <xs:enumeration value="Este"/>
                                                    <xs:enumeration value="Oeste"/>
                                                    <xs:enumeration value="Noreste"/>
                                                    <xs:enumeration value="Noroestee"/>
                                                    <xs:enumeration value="Sureste"/>
                                                    <xs:enumeration value="Suroeste"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="velocidad">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="400"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="temperatura">
                                <xs:complexType>
                                    <xs:sequence>                         
                                        <xs:element name="minimo" type="maxmin"/>
                                        <xs:element name="maximo" type="maxmin"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="fecha" type="xs:date"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== leticiarivlop/2122_LMSGI_LeticiaRL/html/html/ud04/10/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE prediccion [
                <!ELEMENT prediccion (municipio,dia+)>
                <!ATTLIST prediccion
                          xmlns:xsi CDATA #IMPLIED
                          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
                <!ELEMENT municipio (nombre,provincia)>
                <!ATTLIST municipio id ID #REQUIRED>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT provincia (#PCDATA)>
                <!ELEMENT dia (prob_precipitacion,estado_cielo,viento,temperatura)>
                <!ATTLIST dia fecha CDATA #REQUIRED>
                <!ELEMENT prob_precipitacion (#PCDATA)>
                <!ELEMENT estado_cielo (#PCDATA)>
                <!ATTLIST estado_cielo descripcion CDATA #REQUIRED>
                <!ELEMENT viento (direccion,velocidad)>
                <!ELEMENT direccion (#PCDATA)>
                <!ELEMENT velocidad (#PCDATA)>
                <!ELEMENT temperatura (minimo,maximo)>
                <!ELEMENT minimo (#PCDATA)>
                <!ELEMENT maximo (#PCDATA)>
]>

<prediccion xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='10.xsd'>
    <municipio id="Benavente">
        <nombre>Benavente</nombre>
        <provincia>Zamora</provincia>
    </municipio>
    <dia fecha="2022-01-15">
        <prob_precipitacion>10</prob_precipitacion>
        <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Norte</direccion>
            <velocidad>200</velocidad>
        </viento>
        <temperatura>
            <minimo>-3</minimo>
            <maximo>10</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-16">
        <prob_precipitacion>20</prob_precipitacion>
        <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Sur</direccion>
            <velocidad>100</velocidad>
        </viento>
        <temperatura>
            <minimo>2</minimo>
            <maximo>18</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-17">
        <prob_precipitacion>15</prob_precipitacion>
   <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Oeste</direccion>
            <velocidad>150</velocidad>
        </viento>
        <temperatura>
            <minimo>-4</minimo>
            <maximo>2</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-18">
        <prob_precipitacion>24</prob_precipitacion>
      <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Noroestee</direccion>
            <velocidad>125</velocidad>
        </viento>
        <temperatura>
            <minimo>-1</minimo>
            <maximo>5</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-19">
        <prob_precipitacion>56</prob_precipitacion>
        <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Suroeste</direccion>
            <velocidad>120</velocidad>
        </viento>
        <temperatura>
            <minimo>-6</minimo>
            <maximo>0</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-20">
        <prob_precipitacion>0</prob_precipitacion>
       <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Este</direccion>
            <velocidad>100</velocidad>
        </viento>
        <temperatura>
            <minimo>0</minimo>
            <maximo>10</maximo>
        </temperatura>
    </dia>
    <dia fecha="2022-01-21">
        <prob_precipitacion>0</prob_precipitacion>
        <estado_cielo descripcion="Despejado">1</estado_cielo>
        <viento>
            <direccion>Norte</direccion>
            <velocidad>50</velocidad>
        </viento>
        <temperatura>
            <minimo>5</minimo>
            <maximo>18</maximo>
        </temperatura>
    </dia>
</prediccion>
