=== leticiarivlop/2122_LMSGI_LeticiaRL/html/ud04/01/01.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="email">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="remitente" type="xs:string"/>
                <xs:element name="destinatario" type="xs:string" maxOccurs="unbounded"/>
                <xs:element name="fecha" type="xs:date"/>
                <xs:element name="asunto" type="xs:string"/>
                <xs:element name="mensaje" type="xs:string" minOccurs="0"/>
                <xs:element name="fichero" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="tipo" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                    
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== leticiarivlop/2122_LMSGI_LeticiaRL/ud04/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<email
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='01.xsd'>
    <remitente></remitente>
    <destinatario></destinatario>
    <destinatario></destinatario>
    <destinatario></destinatario>
    <fecha></fecha>
    <asunto></asunto>
    <mensaje></mensaje>
    <fichero>
        <nombre></nombre>
        <type></type>
    </fichero>
    <fichero>
        <nombre></nombre>
        <type></type>
    </fichero>
    <fichero>
        <nombre></nombre>
        <type></type>
    </fichero>

</email>

=== leticiarivlop/2122_LMSGI_LeticiaRL/ud04/01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
XML01.- Escribir un documento XML que almacene la información de un mail y contenga la siguiente información: 
remitente, destinatario(s), fecha del mensaje, asunto, mensaje, ficheros adjuntos (por cada fichero debe especificar el 
nombre y el tipo MIME). No utilizar atributos.
-->
 <!DOCTYPE email [
                <!ELEMENT email (remitente,destinatario+,fecha,asunto,mensaje?,fichero+)>
                <!ATTLIST email
                          xmlns:xsi CDATA #IMPLIED
                          xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
                <!ELEMENT remitente (#PCDATA)>
                <!ELEMENT destinatario (#PCDATA)>
                <!ELEMENT fecha (#PCDATA)>
                <!ELEMENT asunto (#PCDATA)>
                <!ELEMENT mensaje (#PCDATA)>
                <!ELEMENT fichero (nombre,tipo)>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT tipo (#PCDATA)>       
]>

<email     
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='01.xsd'>
    <remitente>
        leticia.rivlop@educa.jcyl.es
    </remitente>
    <destinatario>
        victor@educa.jcyl.es
    </destinatario>
    <destinatario>
        david@educa.jcyl.es
    </destinatario>
    <destinatario>
        ricardo@educa.jcyl.es
    </destinatario>
    <destinatario>
        manuel@educa.jcyl.es
    </destinatario>
    <fecha>2022-10-03</fecha>
    <asunto>Fiesta fin de curso</asunto>
    <mensaje>Lugar de la fiesta:Benavente 20:00</mensaje>
    <fichero>
        <nombre>foto1.jpg</nombre>
        <tipo>image/jpeg</tipo>
    </fichero>
    <fichero>
        <nombre>foto2.jpg</nombre>
        <tipo>image/jpeg</tipo>
    </fichero>
</email>
