<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE world [
                <!ELEMENT world (fila+)>
                <!ELEMENT fila (continente,pais,capital)>
                <!ELEMENT continente (#PCDATA)>
                <!ELEMENT pais (#PCDATA)>
                <!ELEMENT capital (#PCDATA)>
]>

<world>
    <fila>
        <continente>
            Europa
        </continente>
        <pais>
            Alemania
        </pais>
        <capital>
            Berlin
        </capital>
    </fila>
    <fila>
        <continente>
            America
        </continente>
        <pais>
            Argentina
        </pais>
        <capital>
            Buenos Aires
        </capital>
    </fila>
    <fila>
        <continente>
           America
        </continente>
        <pais>
            Bahamas
        </pais>
        <capital>
            Nassau
        </capital>
    </fila>
    <fila>
        <continente>
            Asia
        </continente>
        <pais>
            Afganistan
        </pais>
        <capital>
           Kabul
        </capital>
    </fila>
    <fila>
        <continente>
          Asia
        </continente>
        <pais>
           Arabia Saudita
        </pais>
        <capital>
            Riad
        </capital>
    </fila>
</world>
